added MVA updates feature, mva_updates_pool config option added sphMemberLess() binder (userful for Sort() calls) added ARRAY_FOREACH_COND macro added pthreads checks configure (pthreads are required now)
git-svn-id: svn://svn.sphinxsearch.com/sphinx/trunk@1324 406a0c4d-033a-0410-8de8-e80135713968

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4103,7 +4103,8 @@ done
 
 
 
-for ac_header in fcntl.h limits.h netdb.h netinet/in.h stdlib.h string.h sys/file.h sys/socket.h sys/time.h unistd.h
+
+for ac_header in fcntl.h limits.h netdb.h netinet/in.h stdlib.h string.h sys/file.h sys/socket.h sys/time.h unistd.h pthread.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -7616,6 +7617,193 @@ echo "${ECHO_T}configuring Sphinx" >&6
 echo "${ECHO_T}$TMP" >&6
 	echo "$as_me:$LINENO: result: " >&5
 echo "${ECHO_T}" >&6
+
+
+
+# check for pthreads
+
+
+
+# check for needed cflags
+echo "$as_me:$LINENO: checking for CFLAGS needed for pthreads" >&5
+echo $ECHO_N "checking for CFLAGS needed for pthreads... $ECHO_C" >&6
+if test "${pthreads_cflags+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+	save_cflags=$CFLAGS
+	for flag in none -kthread -pthread -pthreads -mt -mthreads -Kthread -threads; do
+		CFLAGS=$save_cflags
+	test "x$flag" != "xnone" && CFLAGS="$CFLAGS $flag"
+
+if test "$cross_compiling" = yes; then
+  pthreads_try_run=no
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <pthread.h>
+#include <stddef.h>
+
+void * thread_routine ( void * data )
+{
+	return data;
+}
+
+int main ()
+{
+	pthread_t thd;
+	pthread_mutexattr_t mattr;
+	pthread_once_t once_init = PTHREAD_ONCE_INIT;
+	int data = 1;
+
+	pthread_mutexattr_init ( &mattr );
+	return pthread_create ( &thd, NULL, thread_routine, &data );
+}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  pthreads_try_run=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+pthreads_try_run=no
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+if test $pthreads_try_run = yes; then
+
+			pthreads_cflags="$flag"
+			break
+
+fi
+
+	done
+	CFLAGS=$save_cflags
+
+fi
+echo "$as_me:$LINENO: result: $pthreads_cflags" >&5
+echo "${ECHO_T}$pthreads_cflags" >&6
+
+if test -n "$pthreads_cflags"; then
+	have_pthreads=yes
+	if test "x$pthreads_cflags" != "xnone"; then
+		CPPFLAGS="$CPPFLAGS $pthreads_cflags"
+	fi
+fi
+
+# check for needed libs
+echo "$as_me:$LINENO: checking for LIBS needed for pthreads" >&5
+echo $ECHO_N "checking for LIBS needed for pthreads... $ECHO_C" >&6
+if test "${pthreads_libs+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+	save_libs=$LIBS
+	for lib in -lpthread -lpthreads -lc_r; do
+	LIBS="$save_libs $lib"
+
+if test "$cross_compiling" = yes; then
+  pthreads_try_run=no
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <pthread.h>
+#include <stddef.h>
+
+void * thread_routine ( void * data )
+{
+	return data;
+}
+
+int main ()
+{
+	pthread_t thd;
+	pthread_mutexattr_t mattr;
+	pthread_once_t once_init = PTHREAD_ONCE_INIT;
+	int data = 1;
+
+	pthread_mutexattr_init ( &mattr );
+	return pthread_create ( &thd, NULL, thread_routine, &data );
+}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  pthreads_try_run=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+pthreads_try_run=no
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+if test $pthreads_try_run = yes; then
+
+		pthreads_libs=$lib
+		break
+
+fi
+
+	done
+	LIBS=$save_libs
+
+fi
+echo "$as_me:$LINENO: result: $pthreads_libs" >&5
+echo "${ECHO_T}$pthreads_libs" >&6
+
+if test -n "$pthreads_libs"; then
+	have_pthreads=yes
+	LIBS="$LIBS $pthreads_libs"
+fi
+
+# final check
+echo "$as_me:$LINENO: checking for pthreads" >&5
+echo $ECHO_N "checking for pthreads... $ECHO_C" >&6
+if test x$have_pthreads = xyes; then
+	echo "$as_me:$LINENO: result: found" >&5
+echo "${ECHO_T}found" >&6
+else
+	{ { echo "$as_me:$LINENO: error: no working pthreads library found" >&5
+echo "$as_me: error: no working pthreads library found" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 # check if we should compile with MySQL support
