better mysql paths/flags detection
git-svn-id: svn://svn.sphinxsearch.com/sphinx/trunk@973 406a0c4d-033a-0410-8de8-e80135713968

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT mysqlconfig MYSQL_LIBS MYSQL_CFLAGS USE_MYSQL_TRUE USE_MYSQL_FALSE pgconfig PGSQL_LIBS PGSQL_CFLAGS USE_PGSQL_TRUE USE_PGSQL_FALSE USE_LIBSTEMMER_TRUE USE_LIBSTEMMER_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB CPP EGREP LIBOBJS CONFDIR LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT MYSQL_LIBS MYSQL_CFLAGS USE_MYSQL_TRUE USE_MYSQL_FALSE pgconfig PGSQL_LIBS PGSQL_CFLAGS USE_PGSQL_TRUE USE_PGSQL_FALSE USE_LIBSTEMMER_TRUE USE_LIBSTEMMER_FALSE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB CPP EGREP LIBOBJS CONFDIR LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -867,10 +867,10 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-mysql            compile with MySQL support (default is enabled)
-  --with-pgsql            compile with PostgreSQL support (default is
-                          disabled)
   --with-mysql-includes   path to MySQL header files
   --with-mysql-libs       path to MySQL libraries
+  --with-pgsql            compile with PostgreSQL support (default is
+                          disabled)
   --with-pgsql-includes   path to PostgreSQL header files
   --with-pgsql-libs       path to PostgreSQL libraries
   --with-libstemmer       compile with libstemmer support (default is
@@ -1829,7 +1829,7 @@ echo "${ECHO_T}$TMP" >&6
 echo "${ECHO_T}" >&6
 
 
-# Check if we should compile with MySQL support
+# check if we should compile with MySQL support
 
 # Check whether --with-mysql or --without-mysql was given.
 if test "${with_mysql+set}" = set; then
@@ -1841,88 +1841,112 @@ else
 fi;
 echo "$as_me:$LINENO: checking whether to compile with MySQL support" >&5
 echo $ECHO_N "checking whether to compile with MySQL support... $ECHO_C" >&6
-if test "${ac_cv_use_mysql+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_use_mysql=no
-fi
-echo "$as_me:$LINENO: result: $ac_cv_use_mysql" >&5
-echo "${ECHO_T}$ac_cv_use_mysql" >&6
-
-# Check if we should compile with PostgreSQL support
-
-# Check whether --with-pgsql or --without-pgsql was given.
-if test "${with_pgsql+set}" = set; then
-  withval="$with_pgsql"
-  ac_cv_use_pgsql=$withval
-else
-  ac_cv_use_pgsql=no
-
-fi;
-echo "$as_me:$LINENO: checking whether to compile with PostgreSQL support" >&5
-echo $ECHO_N "checking whether to compile with PostgreSQL support... $ECHO_C" >&6
-if test "${ac_cv_use_pgsql+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_use_pgsql=yes
-fi
-echo "$as_me:$LINENO: result: $ac_cv_use_pgsql" >&5
-echo "${ECHO_T}$ac_cv_use_pgsql" >&6
-
-
 if test x$ac_cv_use_mysql != xno; then
+	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
 
 
-# check well-known include paths
-for MYSQL_INCLUDE in "/usr/local/mysql/include" "/usr/local/mysql/include/mysql" "/usr/include/mysql"
-do
-	if test  -r "$MYSQL_INCLUDE/mysql.h"
-	then
-		ac_cv_mysql_includes=$MYSQL_INCLUDE
-	fi
-done
+user_mysql_config=
+user_mysql_includes=
+user_mysql_libs=
 
-# check well-known library paths
-for MYSQL_LIB in "/usr/local/mysql/lib" "/usr/local/lib/mysql" "/usr/local/mysql/lib/mysql" "/usr/lib/mysql"
-do
-	if test  -d "$MYSQL_LIB"
-	then
-		ac_cv_mysql_libs=$MYSQL_LIB
-	fi
-done
-
-# if includes and/or libs were not found,
-# check well-known mysqlconfig paths
-if test  -z "$ac_cv_mysql_includes" -o -z "$ac_cv_mysql_libs"
-then
-	for MYSQL_CONFIG in "/usr/local/mysql/bin"
-	do
-		if test  -x "$MYSQL_CONFIG/mysql_config"
-		then
-			mysqlconfig="$MYSQL_CONFIG/mysql_config"
-		fi
-	done
-fi
-
-# check for custom user-specified MySQL root directory
+# check explicit MySQL root for mysql_config, include, lib
 if test  x$ac_cv_use_mysql != xyes -a x$ac_cv_use_mysql != xno
 then
-	ac_cv_mysql_root=`echo $ac_cv_use_mysql | sed -e 's+/$++'`
-	if test  -d "$ac_cv_mysql_root/include" -a -d "$ac_cv_mysql_root/libmysql"
+	mysqlroot=`echo $ac_cv_use_mysql | sed -e 's+/$++'`
+	if test  -x "$mysqlroot/bin/mysql_config"
 	then
-		ac_cv_mysql_includes="$ac_cv_mysql_root/include"
-		ac_cv_mysql_libs="$ac_cv_mysql_root/libmysql"
-	elif test  -x "$ac_cv_mysql_root/bin/mysql_config"
+		# if there's mysql_config, that's the best route
+		user_mysql_config="$mysqlroot/bin/mysql_config"
+	elif test  -d "$mysqlroot/include" -a -d "$mysqlroot/lib"
 	then
-		mysqlconfig="$ac_cv_mysql_root/bin/mysql_config"
+		if test  -d "$mysqlroot/include/mysql"
+		then
+			user_mysql_includes="$mysqlroot/include/mysql"
+		else
+			user_mysql_includes="$mysqlroot/include"
+		fi
+
+		if test  -d "$mysqlroot/lib/mysql"
+		then
+			user_mysql_libs="$mysqlroot/lib/mysql"
+		else
+			user_mysql_libs="$mysqlroot/lib"
+		fi
 	else
-		{ { echo "$as_me:$LINENO: error: invalid MySQL root directory: $ac_cv_mysql_root" >&5
-echo "$as_me: error: invalid MySQL root directory: $ac_cv_mysql_root" >&2;}
+		{ { echo "$as_me:$LINENO: error: invalid MySQL root directory '$mysqlroot'; neither bin/mysql_config, nor include/ and lib/ were found there" >&5
+echo "$as_me: error: invalid MySQL root directory '$mysqlroot'; neither bin/mysql_config, nor include/ and lib/ were found there" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 fi
 
-# check for custom includes path
+
+# try running mysql_config
+echo "$as_me:$LINENO: checking for mysql_config" >&5
+echo $ECHO_N "checking for mysql_config... $ECHO_C" >&6
+for mysqlconfig in "$user_mysql_config" "mysql_config" \
+	"/usr/bin/mysql_config" "/usr/local/bin/mysql_config" \
+	"/usr/local/mysql/bin/mysql_config" "/opt/mysql/bin/mysql_config" "/usr/pkg/bin/mysql_config"
+do
+	if test  -n "$mysqlconfig"
+	then
+		MYSQL_CFLAGS=`${mysqlconfig}z --cflags 2>/dev/null`
+		MYSQL_LIBS=`${mysqlconfig}z --libs 2>/dev/null`
+
+		if test  $? -eq 0
+		then
+			echo "$as_me:$LINENO: result: $mysqlconfig" >&5
+echo "${ECHO_T}$mysqlconfig" >&6
+			mysqlconfig=
+			break
+		else
+			MYSQL_CFLAGS=
+			MYSQL_LIBS=
+		fi
+	fi
+done
+if test  -n "$mysqlconfig"
+then
+	echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+fi
+
+
+# if there's nothing from mysql_config, check well-known include paths
+# explicit overrides will be applied later
+if test  -z "$MYSQL_CFLAGS"
+then
+	for CANDIDATE in "$user_mysql_includes" "/usr/local/mysql/include" "/usr/local/mysql/include/mysql" \
+		"/usr/include/mysql"
+	do
+		if test  -n "$CANDIDATE" -a -r "$CANDIDATE/mysql.h"
+		then
+			MYSQL_CFLAGS="-I$CANDIDATE"
+			break
+		fi
+	done
+fi
+
+
+# if there's nothing from mysql_config, check well-known library paths
+# explicit overrides will be applied later
+if test  -z "$MYSQL_LIBS"
+then
+	for CANDIDATE in "$user_mysql_libs" "/usr/lib64/mysql" \
+		"/usr/local/mysql/lib/mysql" "/usr/local/mysql/lib" \
+		"/usr/local/lib/mysql" "/usr/lib/mysql" \
+		"/opt/mysql/lib/mysql" "/usr/pkg/lib/mysql"
+	do
+		if test  -n "$CANDIDATE" -a -d "$CANDIDATE"
+		then
+			MYSQL_LIBS="-L$CANDIDATE -lmysqlclient -lz"
+			break
+		fi
+	done
+fi
+
+
+# apply explicit include path overrides
 
 # Check whether --with-mysql-includes or --without-mysql-includes was given.
 if test "${with_mysql_includes+set}" = set; then
@@ -1931,19 +1955,11 @@ if test "${with_mysql_includes+set}" = set; then
 fi;
 if test  -n "$ac_cv_mysql_includes"
 then
-	echo "$as_me:$LINENO: checking MySQL includes" >&5
-echo $ECHO_N "checking MySQL includes... $ECHO_C" >&6
-if test "${ac_cv_mysql_includes+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_mysql_includes=""
-fi
-echo "$as_me:$LINENO: result: $ac_cv_mysql_includes" >&5
-echo "${ECHO_T}$ac_cv_mysql_includes" >&6
 	MYSQL_CFLAGS="-I$ac_cv_mysql_includes"
 fi
 
-# check for custom library path
+
+# apply explicit lib path overrides
 
 # Check whether --with-mysql-libs or --without-mysql-libs was given.
 if test "${with_mysql_libs+set}" = set; then
@@ -1955,103 +1971,109 @@ then
 	# Trim trailing '.libs' if user passed it in --with-mysql-libs option
 	ac_cv_mysql_libs=`echo ${ac_cv_mysql_libs} | sed -e 's/.libs$//' \
 		-e 's+.libs/$++'`
-	echo "$as_me:$LINENO: checking MySQL libraries" >&5
-echo $ECHO_N "checking MySQL libraries... $ECHO_C" >&6
-if test "${ac_cv_mysql_libs+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_mysql_libs=""
-fi
-echo "$as_me:$LINENO: result: $ac_cv_mysql_libs" >&5
-echo "${ECHO_T}$ac_cv_mysql_libs" >&6
 	MYSQL_LIBS="-L$ac_cv_mysql_libs -lmysqlclient -lz"
 fi
 
-# if some path is missing, try to autodetermine with mysql_config
-if test  -z "$ac_cv_mysql_includes" -o -z "$ac_cv_mysql_libs"
+
+# now that we did all we could, perform final checks
+echo "$as_me:$LINENO: checking MySQL include files" >&5
+echo $ECHO_N "checking MySQL include files... $ECHO_C" >&6
+if test  -z "$MYSQL_CFLAGS"
 then
-	if test  -z "$mysqlconfig"
-	then
-		# Extract the first word of "mysql_config", so it can be a program name with args.
-set dummy mysql_config; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_mysqlconfig+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $mysqlconfig in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_mysqlconfig="$mysqlconfig" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_mysqlconfig="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
+	{ { echo "$as_me:$LINENO: error: missing include files.
 
-  ;;
-esac
-fi
-mysqlconfig=$ac_cv_path_mysqlconfig
+******************************************************************************
+ERROR: cannot find MySQL include files.
 
-if test -n "$mysqlconfig"; then
-  echo "$as_me:$LINENO: result: $mysqlconfig" >&5
-echo "${ECHO_T}$mysqlconfig" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
+Check that you do have MySQL include files installed.
+The package name is typically 'mysql-devel'.
 
-	fi
-	if test  -z "$mysqlconfig"
-	then
-		{ { echo "$as_me:$LINENO: error: mysql_config executable not found
-********************************************************************************
-ERROR: cannot find MySQL libraries. If you want to compile with MySQL support,
-       you must either specify file locations explicitly using
-       --with-mysql-includes and --with-mysql-libs options, or make sure path to
-       mysql_config is listed in your PATH environment variable. If you want to
-       disable MySQL support, use --without-mysql option.
-********************************************************************************
+If include files are installed on your system, but you are still getting
+this message, you should do one of the following:
+
+1) either specify includes location explicitly, using --with-mysql-includes;
+2) or specify MySQL installation root location explicitly, using --with-mysql;
+3) or make sure that the path to 'mysql_config' program is listed in
+   your PATH environment variable.
+
+To disable MySQL support, use --without-mysql option.
+******************************************************************************
 " >&5
-echo "$as_me: error: mysql_config executable not found
-********************************************************************************
-ERROR: cannot find MySQL libraries. If you want to compile with MySQL support,
-       you must either specify file locations explicitly using
-       --with-mysql-includes and --with-mysql-libs options, or make sure path to
-       mysql_config is listed in your PATH environment variable. If you want to
-       disable MySQL support, use --without-mysql option.
-********************************************************************************
+echo "$as_me: error: missing include files.
+
+******************************************************************************
+ERROR: cannot find MySQL include files.
+
+Check that you do have MySQL include files installed.
+The package name is typically 'mysql-devel'.
+
+If include files are installed on your system, but you are still getting
+this message, you should do one of the following:
+
+1) either specify includes location explicitly, using --with-mysql-includes;
+2) or specify MySQL installation root location explicitly, using --with-mysql;
+3) or make sure that the path to 'mysql_config' program is listed in
+   your PATH environment variable.
+
+To disable MySQL support, use --without-mysql option.
+******************************************************************************
 " >&2;}
    { (exit 1); exit 1; }; }
-	else
-		if test  -z "$ac_cv_mysql_includes"
-		then
-			echo "$as_me:$LINENO: checking MySQL C flags" >&5
-echo $ECHO_N "checking MySQL C flags... $ECHO_C" >&6
-			MYSQL_CFLAGS=`${mysqlconfig} --include`
-			echo "$as_me:$LINENO: result: $MYSQL_CFLAGS" >&5
+else
+	echo "$as_me:$LINENO: result: $MYSQL_CFLAGS" >&5
 echo "${ECHO_T}$MYSQL_CFLAGS" >&6
-		fi
-		if test  -z "$ac_cv_mysql_libs"
-		then
-			echo "$as_me:$LINENO: checking MySQL linker flags" >&5
-echo $ECHO_N "checking MySQL linker flags... $ECHO_C" >&6
-			MYSQL_LIBS=`${mysqlconfig} --libs`
-			echo "$as_me:$LINENO: result: $MYSQL_LIBS" >&5
-echo "${ECHO_T}$MYSQL_LIBS" >&6
-		fi
-	fi
 fi
+
+
+echo "$as_me:$LINENO: checking MySQL libraries" >&5
+echo $ECHO_N "checking MySQL libraries... $ECHO_C" >&6
+if test  -z "$MYSQL_LIBS"
+then
+	{ { echo "$as_me:$LINENO: error: missing libraries.
+
+******************************************************************************
+ERROR: cannot find MySQL libraries.
+
+Check that you do have MySQL libraries installed.
+The package name is typically 'mysql-devel'.
+
+If libraries are installed on your system, but you are still getting
+this message, you should do one of the following:
+
+1) either specify libraries location explicitly, using --with-mysql-libs;
+2) or specify MySQL installation root location explicitly, using --with-mysql;
+3) or make sure that the path to 'mysql_config' program is listed in
+   your PATH environment variable.
+
+To disable MySQL support, use --without-mysql option.
+******************************************************************************
+" >&5
+echo "$as_me: error: missing libraries.
+
+******************************************************************************
+ERROR: cannot find MySQL libraries.
+
+Check that you do have MySQL libraries installed.
+The package name is typically 'mysql-devel'.
+
+If libraries are installed on your system, but you are still getting
+this message, you should do one of the following:
+
+1) either specify libraries location explicitly, using --with-mysql-libs;
+2) or specify MySQL installation root location explicitly, using --with-mysql;
+3) or make sure that the path to 'mysql_config' program is listed in
+   your PATH environment variable.
+
+To disable MySQL support, use --without-mysql option.
+******************************************************************************
+" >&2;}
+   { (exit 1); exit 1; }; }
+else
+	echo "$as_me:$LINENO: result: $MYSQL_LIBS" >&5
+echo "${ECHO_T}$MYSQL_LIBS" >&6
+fi
+
+
 
 
 cat >>confdefs.h <<\_ACEOF
@@ -2060,6 +2082,9 @@ _ACEOF
 
 
 
+else
+	echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
 fi
 
 
@@ -2072,7 +2097,22 @@ else
 fi
 
 
+
+# check if we should compile with PostgreSQL support
+
+# Check whether --with-pgsql or --without-pgsql was given.
+if test "${with_pgsql+set}" = set; then
+  withval="$with_pgsql"
+  ac_cv_use_pgsql=$withval
+else
+  ac_cv_use_pgsql=no
+
+fi;
+echo "$as_me:$LINENO: checking whether to compile with PostgreSQL support" >&5
+echo $ECHO_N "checking whether to compile with PostgreSQL support... $ECHO_C" >&6
 if test x$ac_cv_use_pgsql != xno; then
+	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
 
 
 # Check for custom includes path
@@ -2216,6 +2256,9 @@ _ACEOF
 
 
 
+else
+	echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
 fi
 
 
@@ -2226,6 +2269,7 @@ else
   USE_PGSQL_TRUE='#'
   USE_PGSQL_FALSE=
 fi
+
 
 
 
@@ -8146,7 +8190,6 @@ s,@am__untar@,$am__untar,;t t
 s,@MAINTAINER_MODE_TRUE@,$MAINTAINER_MODE_TRUE,;t t
 s,@MAINTAINER_MODE_FALSE@,$MAINTAINER_MODE_FALSE,;t t
 s,@MAINT@,$MAINT,;t t
-s,@mysqlconfig@,$mysqlconfig,;t t
 s,@MYSQL_LIBS@,$MYSQL_LIBS,;t t
 s,@MYSQL_CFLAGS@,$MYSQL_CFLAGS,;t t
 s,@USE_MYSQL_TRUE@,$USE_MYSQL_TRUE,;t t
