added check for 2nd iconv() arg type
git-svn-id: svn://svn.sphinxsearch.com/sphinx/trunk@1111 406a0c4d-033a-0410-8de8-e80135713968

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8181,6 +8181,89 @@ _ACEOF
 
 	echo "$as_me:$LINENO: result: found" >&5
 echo "${ECHO_T}found" >&6
+
+	echo "$as_me:$LINENO: checking for iconv() arg types" >&5
+echo $ECHO_N "checking for iconv() arg types... $ECHO_C" >&6
+	ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+			#include <iconv.h>
+			#include <stdio.h>
+int
+main ()
+{
+const char * inbuf;
+			iconv_t cd;
+			iconv ( cd, &inbuf, NULL, NULL, NULL );
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  iconv_inbuf_const=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+iconv_inbuf_const=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+	ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+	if test  $iconv_inbuf_const = yes ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define ICONV_INBUF_CONST 1
+_ACEOF
+
+		echo "$as_me:$LINENO: result: const char **" >&5
+echo "${ECHO_T}const char **" >&6
+	else
+
+cat >>confdefs.h <<\_ACEOF
+#define ICONV_INBUF_CONST 0
+_ACEOF
+
+		echo "$as_me:$LINENO: result: char **" >&5
+echo "${ECHO_T}char **" >&6
+	fi
 else
 	echo "$as_me:$LINENO: result: not found" >&5
 echo "${ECHO_T}not found" >&6
