Changes in Github CI. Publishing is commented out

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -36,7 +36,7 @@ jobs:
       - name: Extract Boost to put it to the cache
         if: steps.cache.outputs.cache-hit != 'true'
         run: |
-          wget https://repo.manticoresearch.com/repository/tmp/boost_1_75_0.tgz
+          wget https://repo.manticoresearch.com/repository/ci/boost_1_75_0.tgz
           tar -xf boost_1_75_0.tgz
 
   build_linux_debug:
@@ -102,61 +102,61 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
       - name: Download test report artifacts 1_100
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: debug_test_1_100
           path: .
       - name: Download test report artifacts 101_200
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: debug_test_101_200
           path: .
       - name: Download test report artifacts 201_330
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: debug_test_201_330
           path: .
       - name: Download test report artifacts 331_400
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: debug_test_331_400
           path: .
       - name: Download test report artifacts 401_500
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: debug_test_401_500
           path: .
       - name: Download test report artifacts 501_600
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: debug_test_501_600
           path: .
       - name: Download test report artifacts 601_700
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: debug_test_601_700
           path: .
       - name: Download test report artifacts 701_800
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: debug_test_701_800
           path: .
       - name: Download test report artifacts 801_870
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: debug_test_801_870
           path: .
       - name: Download test report artifacts 871_and_on
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: debug_test_871_and_on
@@ -167,10 +167,10 @@ jobs:
         with:
           files: build/junit*.xml
       - name: Per-test results
-        # IMPORTANT: The value of 3 below should correspond to the test shard count, needs.<job_name>.strategy.job-total doesn't work
+        # IMPORTANT: The value of 10 below should correspond to the test shard count, needs.<job_name>.strategy.job-total doesn't work
         run: |
           for file in build/status*; do echo -n "$file: "; cat "$file"; done
-          grep -o "success" build/status* | wc -l | awk '{exit $1==10?0:1}'
+          grep -o "success" build/status* | wc -l | awk '{if ($1==10) exit 0; else {print "Found only "$1" successful runs out of 10"; exit 1}}'
         shell: bash
       - name: Delete unneded per-shard artifacts
         if: always()
@@ -181,13 +181,13 @@ jobs:
       - name: Upload combined artifacts
         if: always()
         continue-on-error: true
-        uses: ./.github/workflows/upload_artifact_with_retries/
+        uses: manticoresoftware/upload_artifact_with_retries@main
         with:
           name: debug_test_resuls
           path: build
 
   build_linux_release:
-    name: Liniux release build
+    name: Linux release build
     uses: ./.github/workflows/build_template.yml
 
   test_linux_release:
@@ -247,61 +247,61 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
       - name: Download test report artifacts 1_100
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: release_test_1_100
           path: .
       - name: Download test report artifacts 101_200
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: release_test_101_200
           path: .
       - name: Download test report artifacts 201_330
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: release_test_201_330
           path: .
       - name: Download test report artifacts 331_400
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: release_test_331_400
           path: .
       - name: Download test report artifacts 401_500
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: release_test_401_500
           path: .
       - name: Download test report artifacts 501_600
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: release_test_501_600
           path: .
       - name: Download test report artifacts 601_700
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: release_test_601_700
           path: .
       - name: Download test report artifacts 701_800
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: release_test_701_800
           path: .
       - name: Download test report artifacts 801_870
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: release_test_801_870
           path: .
       - name: Download test report artifacts 871_and_on
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: release_test_871_and_on
@@ -312,10 +312,10 @@ jobs:
         with:
           files: build/junit*.xml
       - name: Per-test results
-        # IMPORTANT: The value of 3 below should correspond to the test shard count, needs.<job_name>.strategy.job-total doesn't work
+        # IMPORTANT: The value of 10 below should correspond to the test shard count, needs.<job_name>.strategy.job-total doesn't work
         run: |
           for file in build/status*; do echo -n "$file: "; cat "$file"; done
-          grep -o "success" build/status* | wc -l | awk '{exit $1==10?0:1}'
+          grep -o "success" build/status* | wc -l | awk '{if ($1==10) exit 0; else {print "Found only "$1" successful runs out of 10"; exit 1}}'
         shell: bash
       - name: Delete unneded per-shard artifacts
         if: always()
@@ -326,7 +326,7 @@ jobs:
       - name: Upload combined artifacts
         if: always()
         continue-on-error: true
-        uses: ./.github/workflows/upload_artifact_with_retries/
+        uses: manticoresoftware/upload_artifact_with_retries@main
         with:
           name: release_test_resuls
           path: build
@@ -359,7 +359,6 @@ jobs:
       CTEST_CONFIGURATION_TYPE: Debug
       cache_key: build_windows_x64
       artifact_list: "build/xml build/src/Debug/indexer.exe build/src/Debug/searchd.exe build/src/Debug/tests.exe build/src/gtests/Debug/gmanticoretest.exe build/usr"
-
 
   test_windows:
     name: Windows tests
@@ -396,19 +395,19 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
       - name: Download test report artifacts 1_400
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: windows_test_1_400
           path: .
       - name: Download test report artifacts 401_650
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: windows_test_401_650
           path: .
       - name: Download test report artifacts 651_and_on
-        uses: ./.github/workflows/download_artifact_with_retries/
+        uses: manticoresoftware/download_artifact_with_retries@main
         continue-on-error: true
         with:
           name: windows_test_651_and_on
@@ -424,7 +423,7 @@ jobs:
         # IMPORTANT: The value of 3 below should correspond to the test shard count, needs.<job_name>.strategy.job-total doesn't work
         run: |
           for file in build/status*; do echo -n "$file: "; cat "$file"; done
-          grep -o "success" build/status* | wc -l | awk '{exit $1==3?0:1}'
+          grep -o "success" build/status* | wc -l | awk '{if ($1==3) exit 0; else {print "Found only "$1" successful runs out of 3"; exit 1}}'
         shell: bash
       - name: Delete unneded per-shard artifacts
         if: always()
@@ -435,7 +434,7 @@ jobs:
       - name: Upload combined artifacts
         if: always()
         continue-on-error: true
-        uses: ./.github/workflows/upload_artifact_with_retries/
+        uses: manticoresoftware/upload_artifact_with_retries@main
         with:
           name: windows_test_resuls
           path: build
@@ -512,8 +511,7 @@ jobs:
         cmake -DPACK=1 ..
         cmake --build . --target package
       cache_key: pack_${{ matrix.DISTR }}_${{ matrix.arch }}
-      artifact_list: "build/manticore*rpm"
-
+      artifact_list: "build/manticore*tar.gz"
 
   pack_windows:
     name: Windows x64 package
@@ -529,4 +527,158 @@ jobs:
         cmake -DPACK=1 ..
         cmake --build . --target package
       cache_key: pack_${{ matrix.DISTR }}_${{ matrix.arch }}
-      artifact_list: "build/manticore*rpm"
+      artifact_list: "build/manticore*exe build/manticore*zip"
+
+  # virtual job to simplify the CI
+  # This job depends on all the package preparation jobs that have to pass before we can start publishing packages
+  publish:
+    name: Ready for publishing?
+    runs-on: ubuntu-22.04
+    needs: [pack_debian_ubuntu, pack_rhel, pack_macos, pack_windows]
+    if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'pull_request' && github.event.label.name == 'publish')
+    steps:
+      - run: echo "Ready to publish"
+
+  # publish_debian_ubuntu:
+  #   needs: publish
+  #   runs-on: [self-hosted, Linux, X64]
+  #   strategy:
+  #     fail-fast: true
+  #     matrix:
+  #       DISTR: [bionic, focal, jammy, buster, bullseye, bookworm]
+  #       arch: [x86_64, aarch64]
+  #   name: ${{ matrix.DISTR }} ${{ matrix.arch }} publishing
+  #   steps:
+  #     - uses: manticoresoftware/download_artifact_with_retries@main
+  #       with:
+  #         name: build_${{ matrix.DISTR }}_RelWithDebInfo_${{ matrix.arch }}
+  #         path: .
+  #     - name: Deploy package
+  #       run: |
+  #         curl -sSL https://raw.githubusercontent.com/manticoresoftware/repo_scripts/main/upload_repo_deb > script
+  #         chmod +x script
+  #         DISTRO=${{ matrix.DISTR }} DIGIT_DELIMITER2="-" ./script
+  #       shell: bash
+  #
+  # publish_rhel:
+  #   needs: publish
+  #   runs-on: [self-hosted, Linux, X64]
+  #   strategy:
+  #     fail-fast: true
+  #     matrix:
+  #       DISTR: [7, 8, 9]
+  #       arch: [x86_64, aarch64]
+  #   name: RHEL ${{ matrix.DISTR }} ${{ matrix.arch }} publishing
+  #   steps:
+  #     - uses: manticoresoftware/download_artifact_with_retries@main
+  #       with:
+  #         name: build_rhel${{ matrix.DISTR }}_RelWithDebInfo_${{ matrix.arch }}
+  #         path: .
+  #     - name: Deploy package
+  #       run: |
+  #         curl -sSL https://raw.githubusercontent.com/manticoresoftware/repo_scripts/main/upload_repo_rpm > script
+  #         chmod +x script
+  #         DISTRO=${{ matrix.DISTR }} DIGIT_DELIMITER2="_" ./script
+  #       shell: bash
+  #
+  # publish_macos:
+  #   needs: publish
+  #   runs-on: [self-hosted, Linux, X64]
+  #   strategy:
+  #     fail-fast: true
+  #     matrix:
+  #       arch: [x86_64, arm64]
+  #   name: macos ${{ matrix.arch }} publishing
+  #   steps:
+  #     - uses: manticoresoftware/download_artifact_with_retries@main
+  #       with:
+  #         name: build_macos_RelWithDebInfo_${{ matrix.arch }}
+  #         path: .
+  #     - name: Deploy package
+  #       run: |
+  #         curl -sSL https://raw.githubusercontent.com/manticoresoftware/repo_scripts/main/upload_repo_arc > script
+  #         chmod +x script
+  #         DIGIT_DELIMITER2="-" ./script
+  #       shell: bash
+  #
+  # publish_windows:
+  #   name: Publishing Windows packages to repo.manticoresearch.com
+  #   needs: publish
+  #   runs-on: [self-hosted, Linux, X64]
+  #   steps:
+  #     - uses: manticoresoftware/download_artifact_with_retries@main
+  #       with:
+  #         name: build_windows_RelWithDebInfo_x64
+  #         path: .
+  #     - name: Deploy package
+  #       run: |
+  #         curl -sSL https://raw.githubusercontent.com/manticoresoftware/repo_scripts/main/upload_repo_arc > script
+  #         chmod +x script
+  #         DIGIT_DELIMITER2="-" ./script
+  #       shell: bash
+  #
+  # build_nsis:
+  #   name: Making and publishing Windows NSIS installer
+  #   needs: publish_windows
+  #   runs-on: ubuntu-22.04
+  #   container:
+  #     image: manticoresearch/build_nsis:1.0.0
+  #   env:
+  #     CI_COMMIT_SHA: ${{ github.sha }}
+  #   steps:
+  #     - name: Checkout repository # We have to checkout to access .github/workflows/ in further steps
+  #       uses: actions/checkout@v3
+  #       with:
+  #         token: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Initialization
+  #       # without adding the safe.directory the script fails to do git show ...
+  #       run: git config --global --add safe.directory /__w/manticoresearch/manticoresearch
+  #     - name: Make installer
+  #       # TODO: remove the hardcoded paths /builds/ below
+  #       run: |
+  #         mkdir -p /builds/manticoresearch/dev/build/
+  #         /bin/bash dist/build_dockers/nsis/nsis_src_parser.sh
+  #       shell: bash
+  #     - run: mv /builds/manticoresearch/dev/build build
+  #     - name: Upload artifact
+  #       uses: manticoresoftware/upload_artifact_with_retries@main
+  #       with:
+  #         name: win_installer
+  #         path: build/manticore-*.exe
+  #
+  # publish_nsis:
+  #   name: Publishing Windows NSIS installer to repo.manticoresearch.com
+  #   runs-on: [self-hosted, Linux, X64]
+  #   needs: build_nsis
+  #   if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'pull_request' && github.event.label.name == 'publish')
+  #   steps:
+  #     - uses: manticoresoftware/download_artifact_with_retries@main
+  #       with:
+  #         name: win_installer
+  #         path: .
+  #     - name: Deploy package
+  #       run: |
+  #         wget https://raw.githubusercontent.com/manticoresoftware/repo_scripts/main/upload_repo_arc
+  #         chmod +x upload_repo_arc
+  #         /bin/bash ./upload_repo_arc
+  #       shell: bash
+
+  # build_docker:
+  #   name: Building and pushing docker
+  #   needs: publish_debian_ubuntu
+  #   runs-on: ubuntu-22.04
+  #   env:
+  #     DOCKER_USER: ${{ secrets.DOCKER_USER }}
+  #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+  #     GHCR_USER: ${{ secrets.GHCR_USER }}
+  #     GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}
+  #   steps:
+  #     - name: Checkout repository # We have to checkout to access .github/workflows/ in further steps
+  #       uses: actions/checkout@v3
+  #       with:
+  #         token: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Calculate short commit hash
+  #       id: sha
+  #       run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+  #     - name: Building docker
+  #       run: CI_COMMIT_SHORT_SHA=${{ steps.sha.outputs.sha_short }} /bin/bash dist/dockerhub_deploy.sh
