fix

diff --git a/.github/workflows/publish_template.yml b/.github/workflows/publish_template.yml
--- a/.github/workflows/publish_template.yml
+++ b/.github/workflows/publish_template.yml
@@ -45,13 +45,16 @@ jobs:
       - run: |
           echo "${SSH_KEY}" > ${SSH_KEY_LOCATION}
           chmod 600 ${SSH_KEY_LOCATION}
-      - run: |
-          ls -la ${SSH_KEY_LOCATION}
-          echo ${REMOTE_SERVER}
-          TEMP_DIR=$(ssh -vv -i ${SSH_KEY_LOCATION} ${REMOTE_SERVER} "TEMP_DIR=\$(mktemp -d); if [ -z \"\$TEMP_DIR\" ]; then echo 'Failed to create temporary directory' >&2; exit 1; else echo \$TEMP_DIR; fi")
-      - run: scp -i ${SSH_KEY_LOCATION} build/*.{rpm,deb,tar.gz,exe} ${REMOTE_SERVER}:${TEMP_DIR}/build
-      - run: |
-          ssh -i ${SSH_KEY_LOCATION} ${REMOTE_SERVER} <<EOF
+          cat >>~/.ssh/config <<END
+          Host repo
+            HostName ${REMOTE_SERVER}
+            User root
+            IdentityFile ${SSH_KEY_LOCATION}
+            StrictHostKeyChecking no
+          END
+          TEMP_DIR=$(ssh -vv ${REMOTE_SERVER} "TEMP_DIR=\$(mktemp -d); if [ -z \"\$TEMP_DIR\" ]; then echo 'Failed to create temporary directory' >&2; exit 1; else echo \$TEMP_DIR; fi")
+          scp build/*.{rpm,deb,tar.gz,exe} ${REMOTE_SERVER}:${TEMP_DIR}/build
+          ssh ${REMOTE_SERVER} <<EOF
           cd ${TEMP_DIR}
           curl -sSL https://raw.githubusercontent.com/manticoresoftware/repo_scripts/main/upload_repo_${TYPE} > script
           chmod +x script
