ci: Linux tests parallelization and other minor changes

diff --git a/.github/workflows/test_template.yml b/.github/workflows/test_template.yml
--- a/.github/workflows/test_template.yml
+++ b/.github/workflows/test_template.yml
@@ -25,6 +25,9 @@ on:
       build_artifact_name:
         required: true
         type: string
+      results_name:
+        required: true
+        type: string
       timeout:
         required: false
         type: number
@@ -44,7 +47,7 @@ jobs:
       run:
         shell: bash
     container:
-      image: manticoresearch/ubertests_ctest:3263_20241105
+      image: manticoresearch/ubertests_public:331
       env:
         DIAGNOSTIC: 1
         CACHEB: ../cache
@@ -71,7 +74,7 @@ jobs:
           key: build_linux_x86_64
 
       - name: Download build artifacts
-        uses: manticoresoftware/download_artifact_with_retries@v2
+        uses: manticoresoftware/download_artifact_with_retries@v3
         with:
           name: ${{ inputs.build_artifact_name }}
           path: .
@@ -82,18 +85,23 @@ jobs:
       - name: 🚀 Test
         id: test
         # --timeout may be not working https://gitlab.kitware.com/cmake/cmake/-/issues/23979
+        # use -VV instead of -V to get more verbose output
         run: |
-          ctest -VV -S misc/ctest/gltest.cmake --no-compress-output --timeout 600
+          ctest -V -S misc/ctest/gltest.cmake --no-compress-output --timeout 600
         continue-on-error: true
 
+      - name: Check test results
+        if: always()
+        run: |
+          if [ "${{ steps.test.outcome }}" == "failure" ]; then
+            echo "❌ Tests failed ❌"
+            exit 1
+          fi
+          
       - name: List build files
         if: always()
         run: find build
         continue-on-error: true
-
-      - name: Remember status
-        if: always()
-        run: echo "${{ steps.test.outcome }}" > build/status_${{ inputs.artifact_name }}
 
       - name: Prepare test report xmls
         if: always()
@@ -103,7 +111,18 @@ jobs:
       - name: Upload test artifacts
         if: always()
         continue-on-error: true
-        uses: manticoresoftware/upload_artifact_with_retries@v3
+        uses: manticoresoftware/upload_artifact_with_retries@v4
         with:
           name: ${{ inputs.artifact_name }}
-          path: "build/xml build/test/test_*/report* build/junit*.xml build/test/error*.txt build/test/*log build/status*"
+          path: "build/xml build/junit*.xml build/status* build/test/error*.txt build/test/*log build/test/test_*/report* build/test/rt_*/report* build/test/col_*/report*"
+
+      - name: Publish test results
+        if: always()
+        continue-on-error: true
+        uses: manticoresoftware/publish-unit-test-result-action@v2
+        with:
+          check_name: ${{ inputs.results_name }}
+          files: build/junit*.xml
+          compare_to_earlier_commit: false
+          comment_mode: failures
+  
